In [1]:
import numpy as np

In [3]:
z = np.array([1,2,3,4,5])
print(z)

[1 2 3 4 5]


In [4]:
z

array([1, 2, 3, 4, 5])

In [5]:
z[0]

1

In [6]:
z.shape


(5,)

In [16]:
y = np.array([[1,2,3],[1,2,3],[1,2,3]])
y.shape
x = y.shape = (3,2)
print(x)

ValueError: cannot reshape array of size 9 into shape (3,2)

In [20]:
y = np.array([1,2,3,4,5,6])
y.shape
y.shape = (2,3)
print(y)

[[1 2 3]
 [4 5 6]]


In [21]:
x = [1,2,3]
x.append([1,2,3])
print(x)

[1, 2, 3, [1, 2, 3]]


In [22]:
x = [1,2,3]
x.extend([1,2,3])
print(x)

[1, 2, 3, 1, 2, 3]


In [25]:
print(5//2)

2


In [28]:
arr3 = np.diag([1,2,3,4])
print(arr3)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [29]:
rand_arr3 = np.random.randint(1,100,20)
print(rand_arr3)

[48 54  7 51 63 29 82 34 72 63 45 84 22 38 43 60 36 55 30 64]


In [31]:
rand_arr4 = np.random.randint(1,100,20)
print(rand_arr4)

[13  8 63 15 33 22 32 62 77 17 40 49 89 81 65 13 37 58 35 99]
